import React from 'react'

export default function Contact() {
  return (
    <div>
      <h1>Contact</h1>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates et eligendi corporis alias saepe. Laboriosam dolor adipisci tenetur eos doloribus, a facilis blanditiis repudiandae dolore ducimus. Repudiandae placeat magnam temporibus fugiat reprehenderit ea quidem asperiores eveniet deleniti dolorum. Accusantium eveniet facilis voluptatem pariatur nesciunt consectetur minus atque itaque veritatis sed suscipit tenetur minima odio, optio dolore unde veniam facere ea nulla! Nam omnis dignissimos perferendis. Optio minus obcaecati blanditiis consectetur molestias molestiae error amet assumenda saepe, sunt ab perferendis possimus excepturi suscipit reprehenderit quos ipsum dignissimos tempore! Sit soluta explicabo fugiat, ullam ex labore deserunt. Impedit rem ipsam veritatis aliquid reiciendis veniam libero, voluptatem eaque amet blanditiis dolore atque, nihil excepturi autem aliquam non asperiores molestiae minus aut temporibus fugit dolores saepe eos! Iure iusto modi quasi sunt earum voluptatibus sint, cum, ipsa dolorum a minus exercitationem officia? Dicta officia molestias veritatis ab delectus assumenda, commodi, possimus veniam nam recusandae eligendi quod voluptatem aspernatur quaerat, consequatur enim beatae consequuntur a error dolorem et iure. Laborum ratione pariatur quaerat eum necessitatibus numquam ducimus sed debitis, dolore impedit nostrum at omnis hic fuga deleniti expedita vitae aliquam quam ea commodi? Unde vel dolorem illum voluptatum quas quis consequuntur tempore omnis ut, nisi totam cupiditate quod in sapiente ex deserunt facere autem quaerat fugit. Perspiciatis quasi sunt vel iste natus cumque quidem, molestias, ullam maiores nulla sapiente reprehenderit? Quaerat sapiente quas maiores, voluptatibus nobis libero reiciendis veniam dignissimos accusamus quos ex, tempore repellat, doloremque distinctio velit soluta. Temporibus nisi, natus in dolorum corrupti nobis! Cupiditate sapiente impedit distinctio dolores, vero velit facere consequatur obcaecati quae a molestias quam laudantium eaque commodi. Optio temporibus iste ad voluptates, sequi doloremque repellat sit? Nemo sed recusandae voluptates assumenda eligendi laboriosam consequuntur, at atque, perspiciatis deleniti dignissimos tempore cumque quia temporibus iusto. Sed nulla provident dolores hic.</p>
    </div>
  )
}
